keys:
  - &server_pine age12p8e9ctkuu0qj3j3ka9tkaktn2k3prtrssfzcc8kdut0qsqxfs8sh0vukh
  - &server_sequoia age1ryrkhrdczkvcgs2tuvvlfy4qgsdelwjhthnm88hquv5hntplmplqfuxdm4
  - &admin_alex age1gkagt89wv3z4k3rxp5s0wqwaaml9mlvwfrzfzvh8fnjnwymarpzq5ccs67
  - &admin_liferooter age1w8gl68d3eanxk7s9fzahs7vlyxaj244uk8jcruw74l89c2dy7v5svj4tlp
creation_rules:
  - path_regex: modules/by-name/secrets/common.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *server_sequoia
          - *server_pine
  - path_regex: hosts/sequoia/wireguard-server.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *server_sequoia
  - path_regex: wireguard-clients.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *server_sequoia
